packages:
  - "apps/*"
  - "packages/*"

catalog:
  prettier: ^3.3.3
  typescript: ^5.5.3

  tailwindcss: ^3.4.4
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
